name: â™»ï¸  (US) Validation

on:
  workflow_call:
    inputs:
      destination:
        description: build output destination
        type: string
      version:
        description: 'App version'
        type: string
      deploy:
        description: 'App version structure on artifactory or e-store'
        type: string
      issue_key:
        description: 'task/bug number'
        type: string

jobs:  

  version:
    runs-on: self-hosted
    steps:

    - name: validating default version
      run: |
        if ${{ github.event.inputs.version == '0.0.0' }} 
        then 
          echo "ğŸš« invalid version ${{ github.event.inputs.version }}, please dont use default value"
          exit 1
        fi

    - name: validating empty version
      run: |
        if ${{ github.event.inputs.version == '' }} 
        then 
          echo "ğŸš« invalid empty version, plase provide a value"
          exit 1
        fi

  deploy:
    runs-on: self-hosted
    steps:

    - name:
      run: |
        echo "ğŸš§  WIP deploy ${{ github.event.inputs.deploy }}"

  branch:
    runs-on: self-hosted
    steps:

    - name:
      run: |
        echo "ğŸš§  WIP branch naming ${{ github.ref_name }}"

  issue:
    runs-on: self-hosted    
    steps:

    - name: validate issue_key for artifact 
      if: ${{ github.event.inputs.destination == 'artifact_dev' || github.event.inputs.version == 'artifact_prod_vnv' }}
      run: | 
        if ${{ github.event.inputs.issue_key == '' }} 
        then 
          echo "ğŸš« invalid empty issue, build for artifactory requires a valid Jira Issue key "
          exit 1
        fi
        if ${{ github.event.inputs.issue_key == 'G6X-' }} 
        then 
          echo "ğŸš« invalid issue ${{ github.event.inputs.issue }},please dont use default option"
          exit 1
        fi

    - name: validate issue_key for e-store 
      if: ${{ github.event.inputs.destination == 'e_store_enterprise' || github.event.inputs.destination == 'e_store_prod_vnv' }}
      run: | 
        echo "is for e-store" 
        exit 0    
    
    - name: validate issue_key for app-store
      if: ${{ github.event.inputs.destination == 'app_store' }}
      run: | 
        echo "is for app-store"  
        exit 0